"""initial schema

Revision ID: f5b7b20feab5
Revises: 
Create Date: 2026-06-20 16:26:20.543505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5b7b20feab5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_table('dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('district_count', sa.Integer(), nullable=True),
    sa.Column('area_zero', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('district_master',
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('yuzey_alani_km2', sa.Float(), nullable=True),
    sa.Column('arazi_egimi_yuzde', sa.Float(), nullable=True),
    sa.Column('tesvik_bolgesi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_district_master_province'), 'district_master', ['province'], unique=False)
    op.create_table('saved_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('district_ids', sa.JSON(), nullable=False),
    sa.Column('energy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_project_owner_id'), 'saved_project', ['owner_id'], unique=False)
    op.create_table('daily_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('t2m', sa.Float(), nullable=True),
    sa.Column('rh2m', sa.Float(), nullable=True),
    sa.Column('ws10m', sa.Float(), nullable=True),
    sa.Column('allsky_sfc_sw_dwn', sa.Float(), nullable=True),
    sa.Column('ges_score', sa.Float(), nullable=True),
    sa.Column('res_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district_master.district_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_observation_date'), 'daily_observation', ['date'], unique=False)
    op.create_index(op.f('ix_daily_observation_district_id'), 'daily_observation', ['district_id'], unique=False)
    op.create_table('saved_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('scoring_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['saved_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_scenario_district_id'), 'saved_scenario', ['district_id'], unique=False)
    op.create_index(op.f('ix_saved_scenario_owner_id'), 'saved_scenario', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_scenario_owner_id'), table_name='saved_scenario')
    op.drop_index(op.f('ix_saved_scenario_district_id'), table_name='saved_scenario')
    op.drop_table('saved_scenario')
    op.drop_index(op.f('ix_daily_observation_district_id'), table_name='daily_observation')
    op.drop_index(op.f('ix_daily_observation_date'), table_name='daily_observation')
    op.drop_table('daily_observation')
    op.drop_index(op.f('ix_saved_project_owner_id'), table_name='saved_project')
    op.drop_table('saved_project')
    op.drop_index(op.f('ix_district_master_province'), table_name='district_master')
    op.drop_table('district_master')
    op.drop_table('dataset_version')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
